baseURL = "https://wp2static.com"
languageCode = "en-us"
title = "WP2Static"
theme = "accessible-minimalism"
disableHugoGeneratorInject = true
enableRobotsTXT = true

disableKinds = ["taxonomy", "taxonomyTerm"]

[params.info]
description = "Security & Performance"
title404 = "Nothing's here!"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Download"
    url = "/download/"
    weight = 2
  [[menu.main]]
    name = "Add-ons"
    url = "/addons/"
    weight = 3
  [[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 4
  [[menu.main]]
    name = "Support"
    url = "/support/"
    weight = 5
  [[menu.main]]
    name = "Developers"
    url = "/developers/"
    weight = 6
  [[menu.main]]
    name = "Contributors"
    url = "/contributors/"
    weight = 7
  [[menu.main]]
    name = "Alternatives"
    url = "/alternatives/"
    weight = 8
  [[menu.main]]
    name = "Roadmap"
    url = "/roadmap/"
    weight = 9
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    name = "Your Privacy"
    url = "/your-privacy/"
    weight = 11

[outputs]
  home = ["HTML", "RSS"]
  search = ["HTML", "JSON"]

[[deployment.targets]]
# An arbitrary name for this target.
name = "s3cf"
URL = "s3://wp2static-www?region=us-east-1"
cloudFrontDistributionID = "E1FB46KUMJ1MQM"
